print("Please fill in the blanks below: ")
print("__(name)___'s favorite subject in school is __(subject)___.")
name = input("What is the name? ")
subject= input("what is the subject? ")
print("%s's favorite subject in school is %s."%(name, subject))